### ISSUE TITLE
RegisterAdssBusServer() returning ERROR_NOT_FOUND

### ISSUE THREAD

**Issue by therealkenc** [ionescu007/lxss#10]
I am having a little first-try difficulty with the lxserver sample. `(*iLxInstance)->RegisterAdssBusServer()` is returning `80070490` (ERROR_NOT_FOUND) after a bit of a wait. The registry key is set, and on the client side I am able to open the `/dev/lxss` fd as root, but it (naturally) just blocks on `ioctl(..., IOCTL_ADSS_BUS_CLIENT_CONNECT_SERVER, ...)`. This is on 14971. Any ideas?

**Comment by ionescu007** [comment]
Which version of Windows is this?

**Comment by therealkenc** [comment]
14971.

**Comment by ionescu007** [comment]
I can reproduce similar issues in LxLaunch. Looks like the COM interface may have changed again. Unfortunately, there are no symbols for 14971 :(

**Comment by therealkenc** [comment]
Appreciate you having a look; thank-you.

**Comment by Biswa96** [comment]
@therealkenc This becomes a Windows-Version-Specific feature. Build 18234 has `ConnectAdssBusServer()` but build 18247 hasn't. And the ridiculous change is that WSL devs rename ADSS bus to LxBus :rofl: And if I use `ConnectAdssBusServer()` or `RegisterAdssBusServer()` with a 'rough behavior' LxssManager goes into winter's sleep.

**Comment by therealkenc** [comment]
> This becomes a Windows-Version-Specific feature.

Well, yeah. Rich told you that [in March](https://github.com/Microsoft/WSL/issues/2635#issuecomment-375151900).

**Comment by Biswa96** [comment]
Do you remember the movie 'Inception' and the three layer of dream? Here in WSL it becomes, WslAPIs --> COM --> IOCTLs. WSL devs only change the COM not the IOCTLs. You can see there is a CTL code in my WSLReverse project same as 007's lxss project.

**Comment by Biswa96** [comment]
@therealkenc Do you know any EASY method to detect Windows version? If yes then I can add the COM vtable for this Registered slusher very (now LxBusServer).

**Comment by Biswa96** [comment]
@therealkenc Do you know any EASY method to detect Windows version? If yes then I can add the COM vtable for this RegisterAdssBusServer in 007's repo.

**Comment by therealkenc** [comment]
[This](https://stackoverflow.com/questions/47581146/getting-os-build-version-from-win32-api-c). Get it from `LxssManager.dll` with [`GetFileVersionInfoExW()`](https://docs.microsoft.com/en-us/windows/desktop/api/winver/nf-winver-getfileversioninfoexw).

[Ideally](https://github.com/Microsoft/WSL/issues/1086#issuecomment-249685552) MSFT would be changing the IID Version in the IDL.

**Comment by Biswa96** [comment]
@therealkenc I found three ways to detect Windows version: 1. `GetVersionExW()` 2. `RtlGetVersion()` 3. `LOWORD(NtCurrentPeb()->Reserved9[23])`. @ionescu007 may like the 3rd one.

**Comment by ysc3839** [comment]
@Biswa96 RtlGetNtVersionNumbers
RtlGetNtVersionNumbers actually reads from peb.
![image](https://user-images.githubusercontent.com/12028138/46861221-bf74c900-ce44-11e8-9268-351f79271dbe.png)

**Comment by Biswa96** [comment]
Found another way to (mis)use the LxBus IPC mechanism without registering a Bus server (which ionescu007 didn't show in BHUSA16).

**Comment by Biswa96** [comment]
What would you want to do with LxBus when you realise you can read/write anything with it?
