### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by croemheld** [ionescu007/lxss#16]
As already stated in #3 instructions for compiling the files would be really nice, as I haven't seen a pull request for those which don't use VS. Even with VS I cannot run the lxlauncher because opening the VC++ Project file from lxlauncher opens VS without the lxlauncher.cpp source file. 
Compiling the *.cpp file with standard gcc flags results in many missing headers, such as a missing **comutil.h** or **winternl.h**.

**Comment by Biswa96** [comment]
This project doesn't run in RS3. To compile, if you have latest Visual Studio 2017 you've to change the toolset version to v141 and change the sdk version to 16299 (stable).

**Comment by croemheld** [comment]
@Biswa96 Thanks for your answer!

But I'm a little bit confused now: For developing Windows Drivers (Visual Studio 2015: KDMF) I need to use Visual Studio 2015, because the WDK only exists for 2015 as of now. Does this mean, I need to install VS 2017 too, only for using the new SDK from Fall Creators Update (16299)?

I'm currently using VS 2015 with SDK versions 10586, 14393 and 15063 installed. Running the lxlaunch from VS 2015 with Target Platform Version 15063 gives me the error:

```
C:\Users\CRoemheld\Documents\Visual Studio 2015\Projects\LXSSTools\x64\Debug>lxlaunch.exe /bin/bash -c "ls -al"
LxLaunch v1.3.0 -- (c) Copyright 2016 Alex Ionescu
Visit http://github.com/ionescu007/lxss for more information.

USAGE: LxLaunch [<path to ELF binary>]
       Will launch /usr/bin/python if path not present

Failed to initialize ILxssSession

C:\Users\CRoemheld\Documents\Visual Studio 2015\Projects\LXSSTools\x64\Debug>
```

I wonder if this is due to some wrong SDKs or maybe another reason.

**Comment by Biswa96** [comment]
What Windows build are you using?

**Comment by croemheld** [comment]
The build version is the Fall Creators Update (16299).

**Comment by Biswa96** [comment]
I said this doesn't work in Fall CU.

**Comment by croemheld** [comment]
So whatever SDK I'm going to install this won't work in any way? It all depends on the Windows Build, in this case if you have RS2?

**Comment by Biswa96** [comment]
Ya.
