### ISSUE TITLE
This is neither how the English language works.

### ISSUE THREAD

**Issue by NonsenseInc** [ionescu007/lxss#2]
> annyances
(page 46)

> This is not how the English language works.

**Comment by NonsenseInc** [comment]
But thank you for the informative slides, I really enjoyed them!

**Comment by ionescu007** [comment]
Thanks for pointing out the typo in "annoyances". Can you clarify what is wrong with "analyze"?

I suspect BH will post the recordings after post production in a few months time.

**Comment by NonsenseInc** [comment]
I am sorry abot that "analyze" and I don't know what has gotten into me.
Thanks for the info.

**Comment by ionescu007** [comment]
Fixed with 7f018b9aaa09413a34616320b75c7f98db84f150
