### ISSUE TITLE
The TTY device and the path of I/O from bash.exe to /bin/bash

### ISSUE THREAD

**Issue by fpqc** [ionescu007/lxss#6]
Hiya, quick question, wondering since you've done a lot of RE on this already:

So from what I can deduce, bash.exe consists of two distinct parts:
- Something that translates the UTF-8 characters and xterm escape sequences (or whatever you decide to make your terminfo) into/from little-endian UTF-16 and Windows console escape sequences (because conhost)
- A COM client that attaches to the LXSSManager service's COM interface as a console that corresponds to a TTY device in the Linux instance, but also that you could in theory have a TTY on the Linux side that was  not started by invoking bash.exe.

So I was wondering how is the kernel sharing the ttys from the Linux instance up into the LXSSManager service (and are the TTYs somehow accessible through LXSSManager's COM interface even if the tty was not spawned by a bash.exe instance).  Like, I could imagine that the way you might do it is just have the kernel just have it so the tty driver is just some kind of region of shared memory between the Linux Instance and the LXSSManager, and so basically you are just exporting a bunch of raw text and line data, but maybe this would be stupid and the kernel is sharing memory between the service and the instance on a per-device basis (so the memory regions  associated with non-bash.exe tty devices are not mapped into the service's address space.

Or am I entirely wrong and MS is doing it with one of the other million ways to do IPC in Windows?

Also, have you found any checking at the COM interface that only bash.exe is whitelisted to connect and start a new instance and attach itself to a TTY (however they work)?

Or have I got it all wrong?

Thanks for your time and attention.

**Comment by fpqc** [comment]
I convinced Russ Alexander to document this properly in a blogpost, so we're all good =].

**Comment by ionescu007** [comment]
Hey @fpqc I think version 1.2.0 of LxLaunch will answer most of your questions. As you can see, UTF-8 is now native to the console code in Windows, by using SetConsoleCP(CP_UTF8). The VT-100 support is also new and native to the Windows console, and achieved by using the VT100_EMULATION console mode.

The ttys are basically handled (hah!) by creating a pipe on the WIndows and Linux side, and setting that pipe as the Linux standard-in. ADSS IPC will take care of duplicating that into a linux pipe/tty on the other side. Meanwhile, we then wait for input on the Windows STDIN handle. When input is received, we read the input character, and simply write it back out on the pipe, which Linux will now receive as console input.

**Comment by fpqc** [comment]
Nifty! Thanks, will look at the sourcecode again.
