### ISSUE TITLE
Lxlaunch crashes on an unhandled exception in the "else" case of the RS2 check

### ISSUE THREAD

**Issue by fpqc** [ionescu007/lxss#7]
Hiya,

Saw you updated lxlaunch, and I went to go see what the deal was with it.  Two weird things:

First, the build-number check seems to be looking for build >=15000 to launch with the new method (comments say that build >= 15000 means the build is at least redstone 2).  However, the current latest fast-ring build is 14931, so the conditional fails and we drop into the else half of the conditional.  However, as soon as that happens, it crashes.  The VS15 debugger claims that this is a result of an unhandled exception:

>Exception thrown at 0x00007FF93925BBC0 (ntdll.dll) in lxlaunch.exe: 0xC0000005: Access violation writing location 0x000000000000000B. 

The only thing I did that was maybe possibly questionable was building it against the 14392 SDK instead of the 10581 (iirc?) SDK, but I got a similar crash building against that too.

I also tried forcing it to use the new interface by dropping the check (>=15000) to (>=14500), but this gave another crash in basically the same place (inside of the `if` instead of the `else`, but right after the line:

` hr = ((PLX_INSTANCE_V2)*iLxInstance)->CreateLxProcess` with a similar message.

**Comment by fpqc** [comment]
By the way, as per the thread on the WSL issues page, I've got the error that's getting thrown after dropping that number from 15000 to 14500:

>Unhandled exception at 0x00007FFF85718C42 (rpcrt4.dll) in lxlaunch.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF. occurred

**Comment by ionescu007** [comment]
Which build are you running on, by the way? I tried on my preview build with the 14393 SDK and don't have these problems.

**Comment by fpqc** [comment]
I'm on 14931, building with VS 15 Preview 4 against the 14393 SDK.

**Comment by ionescu007** [comment]
Fixed in c8a6696cb7a8c659816413a49ababedda3a16355
